version: "3"

services:
  postgres:
    image: postgres:12.1-alpine
    ports:
      - "8432:5432"
    environment:
      POSTGRES_DB: checksplitter
      POSTGRES_USER: checksplitter
      POSTGRES_PASSWORD: checksplitter
    volumes:
      - checksplitter-db-data:/var/lib/postgresql/data
volumes:
  checksplitter-db-data: